//Por ahora no estoy seguro de como sea en la bd
export type Especialidad = {id: number; nombre: string}

export const Especialidades: Especialidad[] = [
    { id: 1, nombre: "Medicina General" },
  { id: 2, nombre: "Pediatría" },
  { id: 3, nombre: "Cardiología" },
  { id: 4, nombre: "Dermatología" },
  { id: 5, nombre: "Ginecología y Obstetricia" },
  { id: 6, nombre: "Oftalmología" },
  { id: 7, nombre: "Otorrinolaringología" },
  { id: 8, nombre: "Neurología" },
  { id: 9, nombre: "Psiquiatría" },
  { id: 10, nombre: "Endocrinología" },
  { id: 11, nombre: "Traumatología y Ortopedia" },
  { id: 12, nombre: "Urología" },
  { id: 13, nombre: "Gastroenterología" },
  { id: 14, nombre: "Nefrología" },
  { id: 15, nombre: "Reumatología" },
  { id: 16, nombre: "Oncología" },
  { id: 17, nombre: "Hematología" },
  { id: 18, nombre: "Neumología" },
  { id: 19, nombre: "Infectología" },
  { id: 20, nombre: "Anestesiología" },
  { id: 21, nombre: "Cirugía General" },
  { id: 22, nombre: "Cirugía Plástica y Reconstructiva" },
  { id: 23, nombre: "Radiología e Imagenología" },
  { id: 24, nombre: "Medicina Interna" },
  { id: 25, nombre: "Nutrición Clínica" },
  { id: 26, nombre: "Fisiatría y Rehabilitación" },
  { id: 27, nombre: "Medicina del Trabajo" },
  { id: 28, nombre: "Medicina Forense" },
  { id: 29, nombre: "Alergología e Inmunología" },
  { id: 30, nombre: "Genética Médica" },
]